
services:
  apache2:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./conf/default.conf:/etc/apache2/sites-available/000-default.conf
      - ./www/:/var/www/html
      - ./certs/server.crt:/etc/apache2/server.crt
      - ./certs/server.key:/etc/apache2/server.key